before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0"
  - "export PATH=\"$HOME/.yarn/bin:$PATH\""
install:
  - "yarn run setup"
cache:
  yarn: false
language: node_js
node_js:
  - "10"
  - "7"
  - "8"
  - "6"
  - iojs
script:
  - "yarn run build"
  - "yarn run test"
  - "yarn run package-linux"
  - "yarn run publish"
