language: node_js
node_js:
	- "10"
	- "7"
	- "iojs"

before_install:
	- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
	- export PATH="$HOME/.yarn/bin:$PATH"

cache:
	yarn: false

before_script:
	- yarn run setup

script:
	- yarn run build
	- yarn run test
