image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - ps: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  - choco install yarn
  - yarn run setup

build_script:
  - yarn run build
  - yarn run package-win
